stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python3 src/preprocessing.py
    deps:
    - data/raw
    - src/preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python3 src/feature_engg.py
    deps:
    - data/interim
    - src/feature_engg.py
    outs:
    - data/processed
  model_building:
    cmd: python3 src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json